##
name: Checkmarx AST Github Action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: ${{ github.repository }}
          cx_tenant: beta_nova8
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          additional_params: --apikey ${{ secrets.APIKEY }}
          #additional_params: --threshold sast-high=1
